### ISSUE TITLE
Modified classes dont save in exported jar

### ISSUE THREAD

**Issue by devingDev** [Col-E/recaf-3x-issues#104]
Writing to Exported.jar.
 - Modified classes: 0
 - Modified files: 0
I modified two classes though..
I thought recaf 3 wouldnt have this issue which I had in recaf 2 already ..

**Comment by xxDark** [comment]
Provide video so we can know whats the issue.

**Comment by devingDev** [comment]
https://files.catbox.moe/e2z715.flv

`12:58:48.872 [ContainerContentSource:INFO] Reading from file: C:\jars\Clumps-forge-1.19.1-9.0.0+10.jar
12:58:48.908 [ContentSource:INFO] Read 11 classes, 7 files
12:58:49.136 [CompileDependencyUpdater:INFO] 35 phantom classes were generated
12:59:01.847 [JavacCompiler:ERROR] Compilation of 'com/blamejared/clumps/mixin/MixinExperienceOrb' failed
12:59:11.676 [ExportUtil:INFO] Preparing to write to: C:\jars\export.jar
12:59:11.680 [Exporter:INFO] Writing to export.jar.
 - Modified classes: 0
 - Modified files: 0
12:59:11.687 [Exporter:INFO] Written to export.jar in 6ms. Compression ratio: 46.70%
`

**Comment by Col-E** [comment]
You do see those compiler errors right?
Its not saving.

**Comment by Col-E** [comment]
For a simple change like that it'd be very easy to use the assembler

**Comment by devingDev** [comment]
Alright thank you, I didn't know it was more complicated than just editing the java code.
Tried my way around using the assembler and my own compiled program to find what i should put there.
And it works!
