### ISSUE TITLE
Class icons blinking

### ISSUE THREAD

**Issue by FlowArg** [Col-E/recaf-3x-issues#106]
Hi,
Here is my Recaf and system information:
![image](https://user-images.githubusercontent.com/52298108/183655842-4ec1dccc-9e00-404c-a75a-2a77a7cc1bfb.png)

Quick description:
The class icons flicker when I right click or when I open/close Files item.
Maybe the problem is related to Col-E/Recaf#689 ?

Here is the video:

https://user-images.githubusercontent.com/52298108/183656317-fd69d8a5-024d-4487-a5c9-56a20b36e07a.mp4

**Comment by xxDark** [comment]
Not an issue, icons are created in a different thread so it does not freeze UI thread
Will keep this open for any suggestions though, if someone finds a way to make this blinking not so obvious

**Comment by Col-E** [comment]
Should be addressed now: https://github.com/Col-E/Recaf/pull/596
