### ISSUE TITLE
Improve UX of auto-renamer

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#108]
From: #103

Current design:

![image](https://user-images.githubusercontent.com/21371686/188505069-ef538b33-6dbf-4df8-9323-b23c8e7d8b91.png)

The initial work is done but the UI isn't exactly complete. Not all possible features are there too, but are easy enough to add.

**Comment by Col-E** [comment]
Added some missing features like _"auto-map whitespace names"_ and such, added test coverage for the basics.

**Comment by Amejonah1200** [comment]
Pog
