### ISSUE TITLE
Improve suggestions menu

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#113]
Building off of https://github.com/Col-E/Recaf/pull/564/

![image](https://user-images.githubusercontent.com/21371686/189110031-611e7e0a-5bb1-4c1c-b67f-cece647b2de7.png)

Currently we just do `startsWith`. It may be useful to do a lower-cased `contains` so that users can do lazier completions without having to type out the name of something from the start.

Counter, you may get some additional unwanted results doing a contains search.

**Comment by Amejonah1200** [comment]
+ Add Live Auto-Complete, to avoid needing Ctrl+Space every time

**Comment by Amejonah1200** [comment]
![grafik](https://user-images.githubusercontent.com/50181314/189531338-a3773e60-e46b-4f44-bc1e-296e77cbc941.png)
Bug: here should be suggestions on fields, but it takes `D:` as input

**Comment by Amejonah1200** [comment]
Being addressed in https://github.com/Col-E/Recaf/pull/606
