### ISSUE TITLE
Interface glitched out while renaming stuff

### ISSUE THREAD

**Issue by mr-nv** [Col-E/recaf-3x-issues#132]
![Screenshot_5138](https://user-images.githubusercontent.com/31269663/203654528-172404bf-6312-4550-84d0-58cddcbaf2ab.png)
was renaming class names, methods and fields in a jar when the interface just went full black right after i renamed a field. whats interesting is that the ui was fully responsive (i was able to export the mappings), but it was just black
also the cpu usage went high (20% cpu usage)
![Screenshot_5139](https://user-images.githubusercontent.com/31269663/203655181-a68869ae-5a88-41fe-a63e-1b0727b9a075.png)

**Comment by Col-E** [comment]
Need a sample to reproduce.

**Comment by mr-nv** [comment]
i dont think the problem is in the sample because the glitch occured only after i renamed a lot of stuff, but if you want i can pm you the sample in discord or email
