### ISSUE TITLE
Analyzer thinking that [[I is an integer array, but it's actually an object array

### ISSUE THREAD

**Issue by Geolykt** [Col-E/recaf-3x-issues#136]
Assembler shows problem in class "me.dami.com.customfishing.menus.ManageFishingInventory" for method "clickEvent" that shouldn't be there.

Sample: [CustomFIshing-1.0-SNAPSHOT.jar](https://cdn.discordapp.com/attachments/793081672622407681/1062818865446400010/CustomFIshing-1.0-SNAPSHOT.jar)

Basically related to the analyzer thinking that [[I is an integer array, but it's actually an object array (at least for the purposes of AALOAD)

**Comment by Col-E** [comment]
Pushed to dev3, both addressed
