### ISSUE TITLE
Using the Assembler on classes annotated with annotations (that are annotated with RetentionPolicy.RUNTIME) strips it

### ISSUE THREAD

**Issue by mdo992** [Col-E/recaf-3x-issues#140]
I have a class that looks like this:
```java
@TestAnnotation(
    test1 = "a",
    test2 = "a test",
    test3 = "a real test"
)
public class TestClass {
}
```
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface TestAnnotation {
    String test1();

    String test2();

    String test3();
}
```
I decompile jar, open it in Recaf's assembler and save the bytecode without modifying anything. Closing the assembler and opening the class in the assembler again changes the bytecode and the annotation gets stripped:

![image](https://user-images.githubusercontent.com/89719878/215658105-a0b17b8b-9efd-4e2d-a755-3d68559a3a7b.png)

**Comment by Col-E** [comment]
@Nowilltolife This is fixed on `dev3` right?

**Comment by Nowilltolife** [comment]
i do not see a reason why it should strip them, newest dev3 parses all annotations

**Comment by mdo992** [comment]
I believe I was testing on 3.0.0, i’ll try the latest commit and let you know how it goes later.

**Comment by mdo992** [comment]
This appears to be fixed on the latest commit but it also changes the order here, if that mattered:
![image](https://user-images.githubusercontent.com/89719878/215812599-53de13f0-5f0a-475b-82dc-5c7cadc269bc.png)
