### ISSUE TITLE
Recaf escapes newline when modifying bytecode

### ISSUE THREAD

**Issue by mdo992** [Col-E/recaf-3x-issues#141]
My class looks like this:
```java
public class StringTest {
    static {
        String message = "Hello\nWorld!";
    }
}
```

Putting this through Recaf's assembler and saving (without changing anything) will escape the `\n` to `\\n`:
![image](https://user-images.githubusercontent.com/89719878/215658912-f79f75df-580a-496b-a074-4e6a334f1ba2.png)

**Comment by mdo992** [comment]
This may be a duplicate of #139.

**Comment by Col-E** [comment]
It is, working on a bit of a rewrite at the moment and will address it there.

**Comment by mdo992** [comment]
I just used the latest `dev3` and it works fine.
