### ISSUE TITLE
Multi-Release classes are not dispalyed

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/recaf-3x-issues#149]
The Multi-Release directory `META-INF/versions` is never displayed in recaf

**Comment by Col-E** [comment]
This is known and being addressed in `dev4`, but it is not release ready atm.

**Comment by Col-E** [comment]
![image](https://github.com/Col-E/recaf-3x-issues/assets/21371686/9127fe18-4d26-40b2-9216-e53810d3761a)

https://github.com/Col-E/Recaf/commit/cd1e7263649d94741dbc8ec16311ee799b127d1a
