### ISSUE TITLE
Gui can dissappear

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/recaf-3x-issues#151]
![image](https://github.com/Col-E/recaf-3x-issues/assets/28912031/114e2daa-e8e6-4193-a05e-5491a6b62a82)
I just put a obfuscated jar in there, and the ui stopped rendering completely

idk what I did, but I cannot even reproduce this again...
Also I cannot give you the jar used to try this, because I already rebuilt the project a couple times...

In this state you have to close the gui via a task manager.

**Comment by Col-E** [comment]
>Cannot reproduce
>Cannot give jar

When you can give the sample or reproduce, we can reopen this
