### ISSUE TITLE
[Question] How to open the assembler in 3.x?

### ISSUE THREAD

**Issue by marlester-dev** [Col-E/recaf-3x-issues#152]
In 2.x I could just right click and there's edit with assembler but in 3.x it's not there, I couldn't find it there and in keybindings. Sorry for noob question.

**Comment by Amejonah1200** [comment]
Use the "Fields & Methods" Tab to select the member you want. When parsing fails, you cannot right-click anymore.

**Comment by Amejonah1200** [comment]
![image](https://github.com/Col-E/recaf-3x-issues/assets/50181314/8eec0856-1451-44fa-bb4b-ea0c7cd748a7)

**Comment by Col-E** [comment]
Amejonah's answer is the correct one. The edit button brings up the assembler.
