### ISSUE TITLE
Ability to remove recent items from the recent files menu

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#64]
Adding an `X` button would be nice to clear up clutter in the menu once you're done looking at a file.

**Comment by Col-E** [comment]
Note: adding it via right alignment is proving to be more difficult than first thought.

Each menu item can have a `Node` content but even for nodes marked as filling the parent width, they only are aware of the sum of the widths of the children of the content. So having a `GridPane` or `HBox` with a `Label` and `Button` will only ever be able to compute `label.width + button.width` making it impossible to dynamically align the buttons to the right and have all menu item's buttons line up vertically.

**Comment by win32kbase** [comment]
Current progress in https://github.com/Col-E/Recaf/pull/500

**Comment by Col-E** [comment]
Done in the linked PR, along with some follow up commits
