### ISSUE TITLE
What happened with the class mode "Table"

### ISSUE THREAD

**Issue by ConaII** [Col-E/recaf-3x-issues#65]
It was really useful since decompiler gives me a lot of errors.

**Comment by Col-E** [comment]
https://user-images.githubusercontent.com/21371686/156034764-8b04e372-01a5-4479-9841-1fcbf05ec6a4.mp4

You no longer need to switch modes since all of the fields/methods are immediately accessible at all times, even if the decompile isn't valid output.

**Comment by ConaII** [comment]
Oh, thank you, I didn't see that.

**Comment by ConaII** [comment]
Weird, i can't edit one field that in the 2.0 i was able to with the table mode.

**Comment by ConaII** [comment]
And when i try using the ctrl+f to search in the file, it doens't take me to the line it finds.

**Comment by ConaII** [comment]
![image](https://user-images.githubusercontent.com/72966048/156104111-9b358395-f239-4a4d-b1a6-9f9f3ad0193a.png)

**Comment by ConaII** [comment]
![image](https://user-images.githubusercontent.com/72966048/156104147-6dcfccef-658c-4ace-9298-6264c48c89bc.png)

**Comment by ConaII** [comment]
I can't edit any fields on the 3.0x

**Comment by ConaII** [comment]
INVOKEDYNAMIC run (Lcom/isav/iplugin/Main;)Ljava/lang/Runnable; ${H_META} args[()V, handle[H_INVOKESPECIAL com/isav/iplugin/Main.aR()V], ()V]

This "Main.aR" field doesn't exist in the 3.0 list.

**Comment by Col-E** [comment]
https://user-images.githubusercontent.com/21371686/156105542-88235c44-14d6-4829-952e-d23984b64b16.mp4

**Comment by ConaII** [comment]
Ohh, ok.
It's weird that sometimes i can't open a class, and before i used to be able to edit strings directly from the search function

**Comment by ConaII** [comment]
The thing that doesn't let me open classes some times gives me this error https://pastebin.com/We3c3U2F

**Comment by ConaII** [comment]
https://user-images.githubusercontent.com/72966048/156107716-d984d649-e182-47af-a61c-d9c1384877d4.mp4

As you can see, the search tool doesn't take you to the line it's searching, with long files this makes the search tool totally useless

**Comment by Col-E** [comment]
Seems related to some upstream bugs in the text editor component we use. [A recent release has made some notes in the changelog about 'em](https://github.com/FXMisc/RichTextFX/blob/master/CHANGELOG.md#v0108-2022-02-28). Should be able to update the dependency to resolve this.
