### ISSUE TITLE
Can Not Start Jar

### ISSUE THREAD

**Issue by xiexindev** [Col-E/recaf-3x-issues#98]
log file
[log.txt](https://github.com/Col-E/recaf-3x-issues/files/8999971/log.txt)

**Comment by Col-E** [comment]
Looks like you have some leftover data from Recaf 2X. 

Try deleting the Recaf folder `C:\Users\xiexin\AppData\Roaming\Recaf\` and restarting.

**Comment by xiexindev** [comment]
> Looks like you have some leftover data from Recaf 2X. That _may_ be an issue.
> 
> Try deleting the Recaf folder `C:\Users\xiexin\AppData\Roaming\Recaf\` and restarting 3X.

Delete directory after re-run, still cannot start
[log-2022-06-29.txt](https://github.com/Col-E/recaf-3x-issues/files/9006579/log-2022-06-29.txt)

**Comment by Col-E** [comment]
I just pushed more verbose logging into JavaFX initalization in `dev3`. This should give more insight into why its not loading JFX.

[recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.zip](https://github.com/Col-E/recaf-3x-issues/files/9006762/recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.zip)

**Comment by xiexindev** [comment]
> I just pushed more verbose logging into JavaFX initalization in `dev3`. This should give more insight into why its not loading JFX.
> 
> [recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.zip](https://github.com/Col-E/recaf-3x-issues/files/9006762/recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.zip)

now this version works.
[log-2022-06-29.txt](https://github.com/Col-E/recaf-3x-issues/files/9006889/log-2022-06-29.txt)

From the console information, there was a long pause while downloading
`[JFXInjection/main] INFO : Downloading JFX artifact: https://repo1.maven.org/maven2/org/openjfx/javafx-controls/19-ea+8/javafx-controls-19-ea+8-win.jar`

>Try deleting the Recaf folder C:\Users\xiexin\AppData\Roaming\Recaf\ and restarting 3X.

I followed this advice and tried it several times.
finally the startup was successful

_Maybe_ there's something wrong with my network.

**Comment by Col-E** [comment]
🤔
But yeah it wasn't loading the specific version it was looking for _(older versions are ignored)_ and it probably got confused somehow.
